### ISSUE TITLE
Fatal error if the number is not valid

### ISSUE THREAD

**Issue by mehdi-mahdavi** [pishran/ippanel-client#1]
When sending SMS, if the number is invalid, a fatal error will occur, which is the reason for passing array to Exception,

in fact, in case of an error, the response received from the api side is an array.

https://github.com/pishran/ippanel-client/blob/d72eb615b4a6fda307f8e8e1e057e3006858855e/src/Http.php#L112

**Comment by FaridAghili** [comment]
Thank you, I'll check out.
