### ISSUE TITLE
Wrong fill messages array

### ISSUE THREAD

**Issue by crm24-developer** [pishran/ippanel-client#2]
https://github.com/pishran/ippanel-client/blob/7b24942b9afaf71ee09ad6d9fba464a7d8adeaf4/src/Client.php#L150

`$messages[] = $message;`

**Comment by FaridAghili** [comment]
Thanks for report, I guess it should be:

```php
$messages[] = $msg;
```

**Comment by FaridAghili** [comment]
Fixed in [v1.0.3](https://github.com/pishran/ippanel-client/releases/tag/v1.0.3)
